### ISSUE TITLE
test_cli fails in python3.7

### ISSUE THREAD

**Issue by yutingye** [facebookresearch/FRL-Distributed-ML-Scaffold#1]
test_cli.py has the following errors when I tried to run it with
"python3 -m unittest frldistml.tests.test_cli"

I am using python3.7.

======================================================================
ERROR: test_deserialize (frldistml.tests.test_cli.TestPosixIndexedDatasetReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "frldistml/tests/test_cli.py", line 81, in setUp
    compose_type_arguments(TestArgs, optionalGroup, requiredGroup)
  File "frldistml/scaffold/cli.py", line 175, in compose_type_arguments
    arguments = arguments_from_named_tuple(named_tuple_ref)
  File "frldistml/scaffold/cli.py", line 109, in arguments_from_named_tuple
    optional_subtree=(required == False),
  File "frldistml/scaffold/cli.py", line 132, in arguments_from_named_tuple
    elif issubclass(type, (dict, list)):
TypeError: issubclass() arg 1 must be a class

======================================================================
ERROR: test_get_repro_args (frldistml.tests.test_cli.TestPosixIndexedDatasetReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "frldistml/tests/test_cli.py", line 81, in setUp
    compose_type_arguments(TestArgs, optionalGroup, requiredGroup)
  File "frldistml/scaffold/cli.py", line 175, in compose_type_arguments
    arguments = arguments_from_named_tuple(named_tuple_ref)
  File "frldistml/scaffold/cli.py", line 109, in arguments_from_named_tuple
    optional_subtree=(required == False),
  File "frldistml/scaffold/cli.py", line 132, in arguments_from_named_tuple
    elif issubclass(type, (dict, list)):
TypeError: issubclass() arg 1 must be a class

======================================================================
ERROR: test_reserialize (frldistml.tests.test_cli.TestPosixIndexedDatasetReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "frldistml/tests/test_cli.py", line 81, in setUp
    compose_type_arguments(TestArgs, optionalGroup, requiredGroup)
  File "frldistml/scaffold/cli.py", line 175, in compose_type_arguments
    arguments = arguments_from_named_tuple(named_tuple_ref)
  File "frldistml/scaffold/cli.py", line 109, in arguments_from_named_tuple
    optional_subtree=(required == False),
  File "frldistml/scaffold/cli.py", line 132, in arguments_from_named_tuple
    elif issubclass(type, (dict, list)):
TypeError: issubclass() arg 1 must be a class

**Comment by yutingye** [comment]
I can reproduce the failure with the following code, and can verify it works in python3.6 but not 3.7. 

from typing import NamedTuple, List
class Foo(NamedTuple):
... 	a : List[int] = [1]
... 
issubclass(Foo._field_types['a'], list)

If I change the check against "List" rather than "list", it will lead to a different error in python3.7.

**Comment by fuzic** [comment]
we're running everything on python3.6 for now
